### ISSUE TITLE
Crashes on Gnome 46

### ISSUE THREAD

**Issue by 103sbavert** [fthx/proton-vpn#1]
![image](https://github.com/fthx/proton-vpn/assets/65838896/2abbd626-f224-4d48-8a8d-9e7eb43530f2)

**Comment by fthx** [comment]
I did not hit this.
OS? Extensions installed? Detailed error message (see logs)?

**Comment by fthx** [comment]
Do you use flatpak version?

**Comment by 103sbavert** [comment]
OS: Arch Linux
Extensions: will send soon
Logs: where do I look?
Flatpak: Nope

**Comment by fthx** [comment]
GNOME Logs app
search for 'js' in all messages tab

**Comment by fthx** [comment]
Any update?

**Comment by 103sbavert** [comment]
I'll send in a few hours, I've been busy.

**Comment by 103sbavert** [comment]
logs:

```
Extension proton-vpn@fthx: Error: Invalid value 'undefined' for property body in object initializer.

Stack trace:
  Notification@resource:///org/gnome/shell/ui/messageTray.js:354:9
  notify@resource:///org/gnome/shell/ui/main.js:619:26
  _get_app@file:///home/sbeve72/.local/share/gnome-shell/extensions/proton-vpn@fthx/extension.js:31:18
  enable@file:///home/sbeve72/.local/share/gnome-shell/extensions/proton-vpn@fthx/extension.js:49:14
  _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:266:38
  loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:478:32
  async*_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:786:24
  async*_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:792:48
  _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:827:20
  async*init@resource:///org/gnome/shell/ui/extensionSystem.js:76:14
  _initializeUI@resource:///org/gnome/shell/ui/main.js:303:22
  start@resource:///org/gnome/shell/ui/main.js:175:11
  @resource:///org/gnome/shell/ui/init.js:12:47
  @resource:///org/gnome/shell/ui/init.js:21:20
  
  ```

**Comment by 103sbavert** [comment]
![image](https://github.com/user-attachments/assets/426570ac-aa83-450a-975e-510b5d659f7c)
installed extensions

**Comment by fthx** [comment]
Ok the crash is related to the notification that I did not change for GS 46 (needs two args, for two lines).
But the notification is displayed only if the app has not been found.

What's the way you installed Proton VPN?

**Comment by 103sbavert** [comment]
I used to aur to install the protonvpn's new gtk app.

**Comment by fthx** [comment]
To be clear, did you use DEB package from Proton itself?

**Comment by 103sbavert** [comment]
Nope, the AUR package. I am on Arch Linux.

**Comment by fthx** [comment]
In GS's looking glass, could you try:

`Shell.AppSystem.get_default().lookup_app('protonvpn-app.desktop')`

and paste the result?

**Comment by 103sbavert** [comment]
What is the looking glass? How do I install it on arch linux?

**Comment by fthx** [comment]
Type Alt+F2 then:
lg
That's built in GS.

**Comment by 103sbavert** [comment]
found it:
![image](https://github.com/user-attachments/assets/644c5910-4fd3-4439-8bd2-d6930b2cc02e)

**Comment by fthx** [comment]
Ok so where is the desktop file?

**Comment by 103sbavert** [comment]
Its called protonvpn.desktop on my installation, as opposed to protonvpn-app.desktop. But I think I can easily fix that, unless u have a better idea.

**Comment by fthx** [comment]
So try in LG:

`Shell.AppSystem.get_default().lookup_app('protonvpn.desktop')`

**Comment by fthx** [comment]
It this find the app then I could add a double name search in extension.js.

**Comment by fthx** [comment]
btw maybe the desktop filename has to be changed on AUR side?

**Comment by 103sbavert** [comment]
Yeah that's what I'm thinking. I'll open an issue there, thank you.
